#!/bin/bash

add_keywords()
{
	exiftool -sep "," -Keywords-=$TAGS -Keywords+=$TAGS -overwrite_original $@
}

remove_keywords()
{
	exiftool -sep "," -Keywords-=$TAGS -overwrite_original $@
}

purge_keywords()
{
	exiftool -Keywords= $@
}

show_keywords()
{
	echo $(exiftool -Keywords $@)
}

while getopts "c:t:" opt; do
	case "$opt" in
		c) COMMAND="$OPTARG";;
        t) TAGS="$OPTARG";;
	esac
done

shift $((OPTIND-1))

case "$COMMAND" in
	add) add_keywords $@;;
	remove) remove_keywords $@;;
	purge) purge_keywords $@;;
	show) show_keywords $@;;
esac
